name: number_to_words_nepali
description: A Dart library to convert numbers to their Nepali word representations.
version: 1.0.1
repository: https://github.com/subarnaPdl/number_to_words_nepali
homepage: https://subarnapdl.com.np

environment:
  sdk: '>=2.19.5 <4.0.0'

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.22.0